### ISSUE TITLE
Get Limit Order

### ISSUE THREAD

**Issue by JohnYngson** [scientistnik/btsdex#19]
I have this code:
`BitShares.db.get_limit_orders(base_id,quote_id,50).then(function(result){
// display result
});`

But some results are not match on the DEX... specially the quote amount:
`result.sell_price.quote.amount`

**Comment by JohnYngson** [comment]
> I have this code:
> `BitShares.db.get_limit_orders(base_id,quote_id,50).then(function(result){ // display result });`
> 
> But some results are not match on the DEX... specially the quote amount:
> `result.sell_price.quote.amount`

**Comment by JohnYngson** [comment]
> I have this code:
> `BitShares.db.get_limit_orders(base_id,quote_id,50).then(function(result){ // display result });`
> 
> But some results are not match on the DEX... specially the quote amount:
> `result.sell_price.quote.amount`

**Comment by scientistnik** [comment]
What do you mean not match on the DEX? Give an example please.

`BitShares.db.get_limit_orders` is call [this public API](https://dev.bitshares.works/en/master/api/blockchain_api/database.html#get-limit-orders)

Try to connect to another node and compare results.

**Comment by JohnYngson** [comment]
![dexsell](https://user-images.githubusercontent.com/13908649/53739696-595d1100-3ecd-11e9-831c-5bb3f3d1bd52.PNG)
![sell](https://user-images.githubusercontent.com/13908649/53739697-59f5a780-3ecd-11e9-8a12-ce86da0eb71d.PNG)

When you see the red circle.. they are not match cause the quote amount is not correct.. that's why the computation are messed up..

**Comment by scientistnik** [comment]
This amount is response from the node. Which node are you connecting to? Try change node, and compare results.

For example:
```js
const BitShares = require("btsdex")

const start = () => {
   await BItShares.connect("wss://bitshares.openledger.info/ws")
   
   let orders1 = await BitShares.db.get_limit_orders(base_id,quote_id,50)
   ...

   await BitShares.disconnect()
   await BitShares.connect("wss://btsws.roelandp.nl/ws")

   let orders2 = await BitShares.db.get_limit_orders(base_id,quote_id,50)

   console.log(orders1, order2)
}

start()
```

**Comment by JohnYngson** [comment]
The node is depend on what region of the users... I didn't put a specific node on the codes..

**Comment by scientistnik** [comment]
`btsdex` for default connect to `wss://bitshares.openledger.info/ws`. It is OpenLedger node.
Two pictures above, which node are you connecting to?

If this pictures from clone from `bitshares-ui` site, look in settings page.
