### ISSUE TITLE
Get Order Book

### ISSUE THREAD

**Issue by JohnYngson** [scientistnik/btsdex#20]
Hi, is there any way to add the seller / buyers ID or name on this code result?
`BitShares.db.get_order_book(base_id,quote_id,50).then(function(res){
// DISPLAY RESULT
console.log(res);
});`

![capture](https://user-images.githubusercontent.com/13908649/53979582-39398600-4149-11e9-8bac-5303fd278b8b.PNG)

This is more accurate than the `get_limit_orders`

**Comment by scientistnik** [comment]
`get_order_book` and `get_limit_orders` is database API from node. You may try to offer that [there](https://github.com/bitshares/bitshares-core)

 The library won't add IDs.
